import React, { useState, useEffect } from "react";
import { FileUser, Info, Plus, X } from "lucide-react";
import { CustomSelect } from "../../../components/ui/Select";
import { Country, State, City } from "country-state-city";

const OwnershipDetailsTab = ({ formData, setFormData, errors }) => {
  const [selectedOwnershipIndex, setSelectedOwnershipIndex] = useState(0);

  const ownershipRecords = formData.ownershipDetails || [];
  const allCountries = Country.getAllCountries();

  // Initialize with at least one record if none exist
  useEffect(() => {
    if (ownershipRecords.length === 0) {
      addOwnership();
    }
  }, []);

  const addOwnership = () => {
    const newOwnership = {
      ownerId: "", // Will be generated by backend
      ownershipName: "",
      validFrom: "",
      validTo: "",
      registrationNumber: "",
      registrationDate: "",
      registrationUpto: "",
      purchaseDate: "",
      ownerSrNumber: "",
      stateCode: "",
      rtoCode: "",
      presentAddressId: "",
      permanentAddressId: "",
      saleAmount: 0,
      country: "",
      state: "",
      city: "",
      contactNumber: "",
      email: "",
    };

    const updatedRecords = [...ownershipRecords, newOwnership];
    setFormData((prev) => ({
      ...prev,
      ownershipDetails: updatedRecords,
    }));

    setSelectedOwnershipIndex(ownershipRecords.length);
  };

  const removeOwnership = (index) => {
    if (ownershipRecords.length <= 1) return;

    const updatedRecords = ownershipRecords.filter((_, i) => i !== index);
    let newSelectedIndex = selectedOwnershipIndex;
    if (index === selectedOwnershipIndex) {
      newSelectedIndex = Math.max(0, selectedOwnershipIndex - 1);
    } else if (index < selectedOwnershipIndex) {
      newSelectedIndex = selectedOwnershipIndex - 1;
    }

    setFormData((prev) => ({
      ...prev,
      ownershipDetails: updatedRecords,
    }));

    setSelectedOwnershipIndex(newSelectedIndex);
  };

  const updateOwnership = (index, field, value) => {
    const updatedRecords = [...ownershipRecords];
    updatedRecords[index] = {
      ...updatedRecords[index],
      [field]: value,
    };

    if (field === "country") {
      updatedRecords[index].state = "";
      updatedRecords[index].city = "";
    }

    if (field === "state") {
      updatedRecords[index].city = "";
    }

    setFormData((prev) => ({
      ...prev,
      ownershipDetails: updatedRecords,
    }));
  };

  const getStatesForCountry = (countryName) => {
    if (!countryName) return [];
    const country = allCountries.find((c) => c.name === countryName);
    if (!country) return [];
    return State.getStatesOfCountry(country.isoCode);
  };

  const getCitiesForCountryState = (countryName, stateName) => {
    if (!countryName || !stateName) return [];
    const country = allCountries.find((c) => c.name === countryName);
    if (!country) return [];
    const states = State.getStatesOfCountry(country.isoCode);
    const state = states.find((s) => s.name === stateName);
    if (!state) return [];
    return City.getCitiesOfState(country.isoCode, state.isoCode);
  };

  return (
    <div className="">
      <div className="grid grid-cols-1 gap-4">
        {/* Ownership Records Section */}
        <div className="bg-white rounded-lg shadow-sm">
          <div className="bg-[#0D1A33] text-white px-4 py-3 rounded-t-lg flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileUser className="w-5 h-5" />
              <h2 className="text-lg font-bold">Ownership Details</h2>
            </div>
            <button
              onClick={addOwnership}
              className="bg-[#10B981] text-white h-9 px-3 rounded-lg flex items-center gap-2 text-sm hover:bg-[#059669] transition-colors"
            >
              <Plus className="w-4 h-4" />
              Add
            </button>
          </div>

          <div className="p-6">
            {ownershipRecords.length > 0 ? (
              <div className="overflow-x-auto">
                <table className="w-full min-w-[800px]">
                  <thead>
                    <tr className="text-left text-xs font-medium text-gray-600 border-b border-gray-200">
                      <th className="pb-3 w-12"></th>
                      <th className="pb-3 pl-4 min-w-[200px]">
                        Ownership Name
                      </th>
                      <th className="pb-3 pl-4 min-w-[150px]">Valid From</th>
                      <th className="pb-3 pl-4 min-w-[150px]">Valid To</th>
                      <th className="pb-3 pl-4 min-w-[200px]">
                        Registration Number
                      </th>
                      <th className="pb-3 pl-4 min-w-[150px]">
                        Registration Date
                      </th>
                      <th className="pb-3 pl-4 min-w-[150px]">Purchase Date</th>
                      <th className="pb-3 pl-4 min-w-[150px]">RTO Code</th>
                      <th className="pb-3 pl-4 min-w-[150px]">Sale Amount</th>
                      <th className="pb-3 pl-4 min-w-[200px]">Country</th>
                      <th className="pb-3 pl-4 min-w-[200px]">
                        Contact Number
                      </th>
                      <th className="pb-3 w-12"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {ownershipRecords.map((ownership, index) => {
                      const isSelected = index === selectedOwnershipIndex;

                      return (
                        <tr
                          key={index}
                          className={`${
                            isSelected
                              ? "bg-gray-100 border-l-4 border-l-[#10B981]"
                              : "bg-white"
                          } border-b border-gray-100`}
                          style={{ height: "60px" }}
                        >
                          <td className="px-3">
                            <input
                              type="radio"
                              checked={isSelected}
                              onChange={() => setSelectedOwnershipIndex(index)}
                              className="w-5 h-5 text-[#10B981] border-gray-300 focus:ring-[#10B981]"
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="text"
                              value={ownership.ownershipName || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "ownershipName",
                                  e.target.value
                                )
                              }
                              placeholder="Enter ownership name"
                              className={`min-w-[200px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]?.ownershipName
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="date"
                              value={ownership.validFrom || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "validFrom",
                                  e.target.value
                                )
                              }
                              className={`min-w-[150px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]?.validFrom
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="date"
                              value={ownership.validTo || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "validTo",
                                  e.target.value
                                )
                              }
                              className={`min-w-[150px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]?.validTo
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="text"
                              value={ownership.registrationNumber || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "registrationNumber",
                                  e.target.value.toUpperCase()
                                )
                              }
                              placeholder="MH12AB1234"
                              className={`min-w-[200px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]
                                  ?.registrationNumber
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="date"
                              value={ownership.registrationDate || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "registrationDate",
                                  e.target.value
                                )
                              }
                              className={`min-w-[150px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]
                                  ?.registrationDate
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="date"
                              value={ownership.purchaseDate || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "purchaseDate",
                                  e.target.value
                                )
                              }
                              className={`min-w-[150px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]?.purchaseDate
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="text"
                              value={ownership.rtoCode || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "rtoCode",
                                  e.target.value.toUpperCase()
                                )
                              }
                              placeholder="MH12"
                              className={`min-w-[150px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]?.rtoCode
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="number"
                              value={ownership.saleAmount || 0}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "saleAmount",
                                  parseFloat(e.target.value) || 0
                                )
                              }
                              placeholder="2500000"
                              className={`min-w-[150px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]?.saleAmount
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <CustomSelect
                              key={`country-${index}-${ownership.country}`}
                              value={ownership.country || ""}
                              onValueChange={(value) =>
                                updateOwnership(index, "country", value)
                              }
                              options={allCountries}
                              placeholder="Select Country"
                              searchable
                              getOptionLabel={(option) => option.name}
                              getOptionValue={(option) => option.name}
                              className={`min-w-[200px] text-xs ${
                                errors?.ownershipDetails?.[index]?.country
                                  ? "border-red-500"
                                  : ""
                              }`}
                              error={errors?.ownershipDetails?.[index]?.country}
                            />
                          </td>
                          <td className="px-3">
                            <input
                              type="tel"
                              value={ownership.contactNumber || ""}
                              onChange={(e) =>
                                updateOwnership(
                                  index,
                                  "contactNumber",
                                  e.target.value
                                )
                              }
                              maxLength={10}
                              placeholder="Contact number"
                              className={`min-w-[200px] px-3 py-2 bg-white border rounded-md focus:outline-none focus:ring-2 focus:ring-[#10B981] focus:border-transparent text-xs ${
                                errors?.ownershipDetails?.[index]?.contactNumber
                                  ? "border-red-500"
                                  : "border-gray-300"
                              }`}
                            />
                          </td>
                          <td className="px-3">
                            <button
                              onClick={() => removeOwnership(index)}
                              disabled={ownershipRecords.length <= 1}
                              className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                              <X className="w-4 h-4" />
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="text-center py-12 text-gray-500">
                <FileUser className="w-12 h-12 mx-auto mb-4 text-gray-300" />
                <p className="text-lg font-medium">
                  No ownership records added yet
                </p>
                <p className="text-sm">Click "Add" to get started</p>
              </div>
            )}
          </div>
        </div>

        {/* Info Panel at Bottom */}
        <div className="mt-6 bg-blue-50/50 border border-blue-200/50 rounded-lg p-3 flex items-start gap-2">
          <Info className="w-4 h-4 text-blue-600 mt-0.5 flex-shrink-0" />
          <div className="text-xs text-blue-800">
            <p className="font-semibold mb-1">Ownership Information</p>
            <p>
              Provide accurate ownership and registration details for legal
              compliance. Use the table above to add multiple ownership records.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default OwnershipDetailsTab;
