import React, { useState, useEffect, useCallback } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  RefreshCw,
  Save,
  Upload,
  AlertCircle,
  Truck,
  Gauge,
  Package,
  FileUser,
  Wrench,
  Calendar,
  FileText,
} from "lucide-react";

import { createVehicle, clearError } from "../../redux/slices/vehicleSlice";
import { addToast, openModal } from "../../redux/slices/uiSlice";
import { TOAST_TYPES, ERROR_MESSAGES } from "../../utils/constants";
import { getPageTheme } from "../../theme.config";
import TMSHeader from "../../components/layout/TMSHeader";

// Import tab components
import BasicInformationTab from "./components/BasicInformationTab";
import SpecificationsTab from "./components/SpecificationsTab";
import CapacityDetailsTab from "./components/CapacityDetailsTab";
import OwnershipDetailsTab from "./components/OwnershipDetailsTab";
import MaintenanceHistoryTab from "./components/MaintenanceHistoryTab";
import ServiceFrequencyTab from "./components/ServiceFrequencyTab";
import DocumentsTab from "./components/DocumentsTab";

const CreateVehiclePage = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const theme = getPageTheme("general");

  const { isCreating, error, vehicles } = useSelector((state) => state.vehicle);
  const { user } = useSelector((state) => state.auth);

  const [activeTab, setActiveTab] = useState(0);
  const [formData, setFormData] = useState({
    vehicleId: null, // Will be generated by backend
    basicInformation: {
      registrationNumber: "",
      vin: "",
      vehicleType: "",
      transporterId: "",
      transporterName: "",
      make: "",
      model: "",
      year: new Date().getFullYear(),
      leasingFlag: false,
      leasedFrom: "",
      leaseStartDate: "",
      leaseEndDate: "",
      color: "",
      mileage: 0,
      gpsEnabled: false,
      gpsIMEI: "",
      gpsProvider: "",
      currentDriver: "",
    },
    specifications: {
      engineNumber: "",
      engineCapacity: 0,
      fuelType: "",
      fuelTankCapacity: 0,
      transmission: "",
      noOfGears: 0,
      wheelbase: 0,
      noOfAxles: 0,
      emissionStandard: "",
    },
    capacityDetails: {
      gvw: 0,
      unladenWeight: 0,
      payloadCapacity: 0,
      loadingCapacityVolume: 0,
      loadingCapacityUnit: "CBM",
      cargoLength: 0,
      cargoWidth: 0,
      cargoHeight: 0,
      doorType: "",
      noOfPallets: 0,
    },
    ownershipDetails: {
      ownership: "",
      ownerName: "",
      contactNumber: "",
      email: "",
      purchaseDate: "",
      purchasePrice: 0,
      registrationDate: "",
      registrationAuthority: "",
      rtoCode: "",
      chassisNumber: "",
      permitType: "",
      permitValidTill: "",
    },
    maintenanceHistory: {
      lastServiceDate: "",
      nextServiceDue: "",
      lastInspectionDate: "",
      totalServiceExpense: 0,
      maintenanceNotes: "",
    },
    serviceFrequency: {
      serviceIntervalKM: 0,
      serviceIntervalMonths: 0,
      inspectionFrequencyMonths: 0,
    },
    documents: [
      {
        documentType: "",
        documentNumber: "",
        issueDate: "",
        expiryDate: "",
        issuingAuthority: "",
        country: "",
        state: "",
        status: true,
        fileName: "",
        fileType: "",
        fileData: "",
      },
    ],
    status: "PENDING_APPROVAL",
    createdBy: user?.userId || "ADMIN001",
    createdAt: new Date().toISOString(),
  });

  const [validationErrors, setValidationErrors] = useState({});
  const [tabErrors, setTabErrors] = useState({
    0: false, // Basic Information
    1: false, // Specifications
    2: false, // Capacity Details
    3: false, // Ownership Details
    4: false, // Maintenance History
    5: false, // Service Frequency
    6: false, // Documents
  });

  const tabs = [
    {
      id: 0,
      name: "Basic Information",
      icon: Truck,
      component: BasicInformationTab,
    },
    {
      id: 1,
      name: "Specifications",
      icon: Gauge,
      component: SpecificationsTab,
    },
    {
      id: 2,
      name: "Capacity Details",
      icon: Package,
      component: CapacityDetailsTab,
    },
    {
      id: 3,
      name: "Ownership Details",
      icon: FileUser,
      component: OwnershipDetailsTab,
    },
    {
      id: 4,
      name: "Maintenance History",
      icon: Wrench,
      component: MaintenanceHistoryTab,
    },
    {
      id: 5,
      name: "Service Frequency",
      icon: Calendar,
      component: ServiceFrequencyTab,
    },
    {
      id: 6,
      name: "Documents",
      icon: FileText,
      component: DocumentsTab,
    },
  ];

  // Clear any previous errors on mount
  useEffect(() => {
    dispatch(clearError());
  }, [dispatch]);

  const handleClear = () => {
    if (window.confirm("Are you sure you want to clear all data? This action cannot be undone.")) {
      setFormData({
        vehicleId: null,
        basicInformation: {
          registrationNumber: "",
          vin: "",
          vehicleType: "",
          transporterId: "",
          transporterName: "",
          make: "",
          model: "",
          year: new Date().getFullYear(),
          leasingFlag: false,
          leasedFrom: "",
          leaseStartDate: "",
          leaseEndDate: "",
          color: "",
          mileage: 0,
          gpsEnabled: false,
          gpsIMEI: "",
          gpsProvider: "",
          currentDriver: "",
        },
        specifications: {
          engineNumber: "",
          engineCapacity: 0,
          fuelType: "",
          fuelTankCapacity: 0,
          transmission: "",
          noOfGears: 0,
          wheelbase: 0,
          noOfAxles: 0,
          emissionStandard: "",
        },
        capacityDetails: {
          gvw: 0,
          unladenWeight: 0,
          payloadCapacity: 0,
          loadingCapacityVolume: 0,
          loadingCapacityUnit: "CBM",
          cargoLength: 0,
          cargoWidth: 0,
          cargoHeight: 0,
          doorType: "",
          noOfPallets: 0,
        },
        ownershipDetails: {
          ownership: "",
          ownerName: "",
          contactNumber: "",
          email: "",
          purchaseDate: "",
          purchasePrice: 0,
          registrationDate: "",
          registrationAuthority: "",
          rtoCode: "",
          chassisNumber: "",
          permitType: "",
          permitValidTill: "",
        },
        maintenanceHistory: {
          lastServiceDate: "",
          nextServiceDue: "",
          lastInspectionDate: "",
          totalServiceExpense: 0,
          maintenanceNotes: "",
        },
        serviceFrequency: {
          serviceIntervalKM: 0,
          serviceIntervalMonths: 0,
          inspectionFrequencyMonths: 0,
        },
        documents: [
          {
            documentType: "",
            documentNumber: "",
            issueDate: "",
            expiryDate: "",
            issuingAuthority: "",
            country: "",
            state: "",
            status: true,
            fileName: "",
            fileType: "",
            fileData: "",
          },
        ],
        status: "PENDING_APPROVAL",
        createdBy: user?.userId || "ADMIN001",
        createdAt: new Date().toISOString(),
      });
      setValidationErrors({});
      setTabErrors({
        0: false,
        1: false,
        2: false,
        3: false,
        4: false,
        5: false,
        6: false,
      });
      setActiveTab(0);
    }
  };

  const validateAllTabs = () => {
    const errors = {};
    const errorMessages = [];

    // Basic Information validation
    if (!formData.basicInformation.registrationNumber?.trim()) {
      errors.registrationNumber = "Registration number is required";
      errorMessages.push("Registration number is required");
    }
    if (!formData.basicInformation.vehicleType) {
      errors.vehicleType = "Vehicle type is required";
      errorMessages.push("Vehicle type is required");
    }
    if (!formData.basicInformation.make?.trim()) {
      errors.make = "Make is required";
      errorMessages.push("Make is required");
    }
    if (!formData.basicInformation.model?.trim()) {
      errors.model = "Model is required";
      errorMessages.push("Model is required");
    }

    // Specifications validation
    if (!formData.specifications.engineNumber?.trim()) {
      errors.engineNumber = "Engine number is required";
      errorMessages.push("Engine number is required");
    }
    if (!formData.specifications.fuelType) {
      errors.fuelType = "Fuel type is required";
      errorMessages.push("Fuel type is required");
    }
    if (!formData.specifications.transmission) {
      errors.transmission = "Transmission type is required";
      errorMessages.push("Transmission type is required");
    }

    // Capacity Details validation
    if (!formData.capacityDetails.gvw || formData.capacityDetails.gvw <= 0) {
      errors.gvw = "GVW is required and must be greater than 0";
      errorMessages.push("GVW is required and must be greater than 0");
    }
    if (!formData.capacityDetails.payloadCapacity || formData.capacityDetails.payloadCapacity <= 0) {
      errors.payloadCapacity = "Payload capacity is required";
      errorMessages.push("Payload capacity is required");
    }

    // Ownership Details validation
    if (!formData.ownershipDetails.ownership) {
      errors.ownership = "Ownership type is required";
      errorMessages.push("Ownership type is required");
    }
    if (!formData.ownershipDetails.ownerName?.trim()) {
      errors.ownerName = "Owner name is required";
      errorMessages.push("Owner name is required");
    }
    if (!formData.ownershipDetails.chassisNumber?.trim()) {
      errors.chassisNumber = "Chassis number is required";
      errorMessages.push("Chassis number is required");
    }

    // Determine which tabs have errors
    const newTabErrors = {
      0: !!(errors.registrationNumber || errors.vehicleType || errors.make || errors.model),
      1: !!(errors.engineNumber || errors.fuelType || errors.transmission),
      2: !!(errors.gvw || errors.payloadCapacity),
      3: !!(errors.ownership || errors.ownerName || errors.chassisNumber),
      4: false, // Maintenance History - optional
      5: false, // Service Frequency - optional
      6: false, // Documents - optional
    };

    setTabErrors(newTabErrors);
    setValidationErrors(errors);

    // Find the first tab with errors and switch to it
    if (Object.values(newTabErrors).some(hasError => hasError)) {
      const firstErrorTab = Object.keys(newTabErrors).find(tabId => newTabErrors[tabId]);
      if (firstErrorTab !== undefined) {
        setActiveTab(parseInt(firstErrorTab));
      }
    }

    return { isValid: Object.keys(errors).length === 0, errorMessages };
  };

  const handleSubmit = async () => {
    // Clear previous errors
    setValidationErrors({});
    setTabErrors({
      0: false,
      1: false,
      2: false,
      3: false,
      4: false,
      5: false,
      6: false,
    });

    // Validate entire form
    const { isValid, errorMessages } = validateAllTabs();

    if (!isValid) {
      // Get unique error messages (limit to first 5 for readability)
      const uniqueErrors = [...new Set(errorMessages)].slice(0, 5);

      // Show toast notification with error details
      dispatch(addToast({
        type: TOAST_TYPES.ERROR,
        message: ERROR_MESSAGES.VALIDATION_ERROR || "Please fix validation errors before submitting",
        details: uniqueErrors,
        duration: 8000,
      }));

      return;
    }

    try {
      const result = await dispatch(createVehicle(formData)).unwrap();
      
      dispatch(addToast({
        type: TOAST_TYPES.SUCCESS,
        message: `Vehicle created successfully!`,
        duration: 5000,
      }));

      setTimeout(() => {
        navigate(`/vehicle/${result.vehicleId}`);
      }, 1500);
    } catch (err) {
      dispatch(addToast({
        type: TOAST_TYPES.ERROR,
        message: "Failed to create vehicle",
        details: [err.message || "An error occurred"],
        duration: 5000,
      }));
    }
  };

  const handleBulkUpload = useCallback(() => {
    dispatch(openModal());
  }, [dispatch]);

  return (
    <div className="bg-gradient-to-br from-[#F5F7FA] via-[#F8FAFC] to-[#F1F5F9]">
      <TMSHeader theme={theme} />
      
      {/* Modern Header Bar with glassmorphism */}
      <div className="bg-gradient-to-r from-[#0D1A33] via-[#1A2B47] to-[#0D1A33] px-6 py-4 shadow-xl relative overflow-hidden">
        {/* Background decoration */}
        <div className="absolute inset-0 bg-gradient-to-r from-blue-600/10 via-transparent to-blue-800/10"></div>
        <div className="absolute -top-4 -right-4 w-32 h-32 bg-gradient-to-br from-white/5 to-transparent rounded-full blur-2xl"></div>
        <div className="absolute -bottom-4 -left-4 w-40 h-40 bg-gradient-to-tr from-blue-400/10 to-transparent rounded-full blur-2xl"></div>

        <div className="relative flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button
              onClick={() => navigate(-1)}
              className="group p-2 bg-white/10 backdrop-blur-sm rounded-xl hover:bg-white/20 transition-all duration-300 hover:scale-105 border border-white/20"
            >
              <ArrowLeft className="w-5 h-5 text-white group-hover:text-white transition-colors" />
            </button>

            <div className="space-y-1">
              <h1 className="text-2xl font-bold text-white tracking-tight">
                Create New Vehicle
              </h1>
              <p className="text-blue-100/80 text-xs font-medium">
                Complete all sections to create a comprehensive vehicle profile
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleClear}
              disabled={isCreating}
              className="group inline-flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur-sm text-white border border-white/20 rounded-xl font-medium text-sm hover:bg-white/20 transition-all duration-300 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
            >
              <RefreshCw className="w-4 h-4 group-hover:rotate-180 transition-transform duration-500" />
              Clear
            </button>

            <button
              onClick={handleBulkUpload}
              disabled={isCreating}
              className="group inline-flex items-center gap-2 px-5 py-2.5 bg-white/10 backdrop-blur-sm text-white border border-white/20 rounded-xl font-medium hover:bg-white/20 transition-all duration-300 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
            >
              <Upload className="w-4 h-4 group-hover:scale-110 transition-transform duration-200" />
              Bulk Upload
            </button>

            <button
              onClick={handleSubmit}
              disabled={isCreating}
              className="group inline-flex items-center gap-2 px-5 py-2 bg-gradient-to-r from-[#10B981] to-[#059669] text-white rounded-xl font-medium text-sm hover:from-[#059669] hover:to-[#10B981] transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-green-500/25 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
            >
              {isCreating ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  Creating...
                </>
              ) : (
                <>
                  <Save className="w-4 h-4 group-hover:scale-110 transition-transform duration-200" />
                  Submit
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Modern Tab Navigation with glassmorphism */}
      <div className="bg-gradient-to-r from-[#0D1A33] to-[#1A2B47] px-6 relative">
        {/* Tab backdrop blur effect */}
        <div className="absolute inset-0 bg-gradient-to-r from-[#0D1A33] to-[#1A2B47] backdrop-blur-sm"></div>

        <div className="relative flex space-x-2 py-2">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            const isActive = activeTab === tab.id;
            const hasError = tabErrors[tab.id];

            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`text-nowrap group relative px-6 py-3 font-medium text-sm rounded-t-2xl transition-all duration-300 flex items-center gap-3 ${
                  isActive
                    ? "bg-gradient-to-br from-white via-white to-gray-50 text-[#0D1A33] shadow-lg transform -translate-y-1 scale-105"
                    : "bg-white/5 backdrop-blur-sm text-blue-100/80 hover:bg-white/10 hover:text-white border border-white/10 hover:border-white/20"
                }`}
              >
                {/* Active tab decoration */}
                {isActive && (
                  <div className="absolute inset-x-0 -bottom-0 h-1 bg-gradient-to-r from-[#10B981] to-[#059669] rounded-t-full"></div>
                )}

                {/* Error indicator */}
                {hasError && (
                  <div className="absolute -top-1 -right-1 w-5 h-5 bg-red-500 rounded-full flex items-center justify-center shadow-lg animate-pulse">
                    <AlertCircle className="w-3 h-3 text-white" />
                  </div>
                )}

                <Icon
                  className={`w-5 h-5 transition-all duration-300 ${
                    isActive
                      ? "text-[#10B981] scale-110"
                      : hasError
                      ? "text-red-300 group-hover:text-red-200"
                      : "text-blue-200/70 group-hover:text-white group-hover:scale-105"
                  }`}
                />
                <span className="font-semibold tracking-wide">{tab.name}</span>

                {/* Hover glow effect */}
                {!isActive && (
                  <div className="absolute inset-0 rounded-t-2xl bg-gradient-to-r from-white/0 via-white/5 to-white/0 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Modern Content Area */}
      <div className="px-0 rounded-none py-0 space-y-4">
        {/* Enhanced Tab Content Container */}
        <div className="relative">
          {tabs.map((tab) => {
            const TabComponent = tab.component;
            const isActive = activeTab === tab.id;

            return (
              <div
                key={tab.id}
                className={`transition-all duration-500 ease-in-out ${
                  isActive
                    ? "block opacity-100 transform translate-y-0"
                    : "hidden opacity-0 transform translate-y-4"
                }`}
              >
                {/* Content wrapper with modern styling */}
                <div className="bg-white/60 backdrop-blur-sm rounded-b-3xl shadow-xl border border-white/40 overflow-hidden">
                  {/* Tab content */}
                  <div className="p-4">
                    <TabComponent
                      formData={formData}
                      setFormData={setFormData}
                      errors={validationErrors}
                    />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default CreateVehiclePage;
