exports.up = async function (knex) {
  const now = new Date();
  const createdBy = "SYSTEM";
  const status = "ACTIVE";

  // Insert document types
  await knex("document_type_master").insert([
    {
      document_type_id: "DTM001",
      document_type: "PAN/TIN",
      description: "Permanent Account Number or Tax Identification Number",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM002",
      document_type: "Aadhar Card",
      description: "Aadhar Card",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM003",
      document_type: "TAN",
      description: "Tax Deduction Account Number",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM004",
      document_type: "GSTIN Document",
      description: "Goods and Services Tax Identification Number",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM005",
      document_type: "VAT Certificate",
      description: "Value Added Tax Certificate",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM006",
      document_type: "Any License",
      description: "Any License",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM007",
      document_type: "Any Agreement Document",
      description: "Any Agreement Document",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM008",
      document_type: "Contact Person ID Proof",
      description: "Contact Person ID Proof",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM009",
      document_type: "NDA",
      description: "Non-Disclosure Agreement",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM010",
      document_type: "Vehicle Insurance",
      description: "Vehicle Insurance Document",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM011",
      document_type: "PUC Certificate",
      description: "Pollution Under Control Certificate",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM012",
      document_type: "Permit Certificate",
      description: "Vehicle Permit Certificate",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM013",
      document_type: "Fitness Certificate",
      description: "Vehicle Fitness Certificate",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
  ]);

  // Insert document names
  await knex("document_name_master").insert([
    {
      doc_name_master_id: "DN001",
      document_name: "PAN Card",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN002",
      document_name: "Aadhar Card",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN003",
      document_name: "TAN",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN004",
      document_name: "GSTIN Document",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN005",
      document_name: "VAT Certificate",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN006",
      document_name: "Any License",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN007",
      document_name: "Any Agreement Document",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN008",
      document_name: "Contact Person ID Proof",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN009",
      document_name: "Vehicle Insurance",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN010",
      document_name: "PUC certificate",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN011",
      document_name: "Permit certificate",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      doc_name_master_id: "DN012",
      document_name: "Fitness Certificate",
      user_type: "TRANSPORTER",
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
  ]);

  // Insert document type configurations (linking document names to types)
  await knex("doc_type_configuration").insert([
    {
      document_type_id: "DTM001",
      doc_name_master_id: "DN001",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM002",
      doc_name_master_id: "DN002",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: true, // Aadhar Card is mandatory
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM003",
      doc_name_master_id: "DN003",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM004",
      doc_name_master_id: "DN004",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: true, // GSTIN Document is mandatory
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM005",
      doc_name_master_id: "DN005",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM006",
      doc_name_master_id: "DN006",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM007",
      doc_name_master_id: "DN007",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM008",
      doc_name_master_id: "DN008",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM009",
      doc_name_master_id: "DN009",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM010",
      doc_name_master_id: "DN009",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM011",
      doc_name_master_id: "DN010",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM012",
      doc_name_master_id: "DN011",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
    {
      document_type_id: "DTM013",
      doc_name_master_id: "DN012",
      user_type: "TRANSPORTER",
      service_area_country: null,
      is_mandatory: false,
      is_expiry_required: true,
      is_verification_required: true,
      created_at: now,
      created_on: now,
      created_by: createdBy,
      updated_at: now,
      updated_on: now,
      updated_by: createdBy,
      status: status,
    },
  ]);
};

exports.down = async function (knex) {
  // Delete in reverse order due to foreign key dependencies
  await knex("doc_type_configuration")
    .whereIn("document_type_id", [
      "DTM001",
      "DTM002",
      "DTM003",
      "DTM004",
      "DTM005",
      "DTM006",
      "DTM007",
      "DTM008",
      "DTM009",
      "DTM010",
      "DTM011",
      "DTM012",
      "DTM013",
    ])
    .del();

  await knex("document_name_master")
    .whereIn("doc_name_master_id", [
      "DN001",
      "DN002",
      "DN003",
      "DN004",
      "DN005",
      "DN006",
      "DN007",
      "DN008",
      "DN009",
      "DN010",
      "DN011",
      "DN012",
    ])
    .del();

  await knex("document_type_master")
    .whereIn("document_type_id", [
      "DTM001",
      "DTM002",
      "DTM003",
      "DTM004",
      "DTM005",
      "DTM006",
      "DTM007",
      "DTM008",
      "DTM009",
      "DTM010",
      "DTM011",
      "DTM012",
      "DTM013",
    ])
    .del();
};
