exports.seed = async function (knex) {
  const now = new Date();
  const consignorId = "CONS001";

  console.log(" Seeding warehouse sample data...");

  // Delete existing sample warehouses
  await knex("warehouse_basic_information")
    .where("warehouse_id", "like", "WH00%")
    .del();

  // Insert 5 diverse warehouses across India
  await knex("warehouse_basic_information").insert([
    {
      warehouse_id: "WH001",
      consignor_id: consignorId,
      warehouse_type: "Manufacturing",
      warehouse_name1: "Mumbai Central Manufacturing Hub",
      warehouse_name2: "MCM Hub",
      language: "English",
      vehicle_capacity: 50,
      virtual_yard_in: true,
      radius_for_virtual_yard_in: 2.5,
      speed_limit: 20,
      weigh_bridge_availability: true,
      gatepass_system_available: true,
      fuel_availability: false,
      staging_area_for_goods_organization: true,
      driver_waiting_area: true,
      gate_in_checklist_auth: true,
      gate_out_checklist_auth: true,
      warehouse_address_id: null,
      region: "West",
      zone: "Mumbai Metro",
      created_at: now,
      created_on: now,
      created_by: "SYSTEM",
      updated_at: now,
      updated_on: now,
      updated_by: "SYSTEM",
      status: "PENDING",
    },
    {
      warehouse_id: "WH002",
      consignor_id: consignorId,
      warehouse_type: "Cold Storage",
      warehouse_name1: "Chennai Cold Storage Facility",
      warehouse_name2: "Chennai CS",
      language: "English",
      vehicle_capacity: 30,
      virtual_yard_in: false,
      radius_for_virtual_yard_in: null,
      speed_limit: 15,
      weigh_bridge_availability: true,
      gatepass_system_available: true,
      fuel_availability: false,
      staging_area_for_goods_organization: true,
      driver_waiting_area: false,
      gate_in_checklist_auth: true,
      gate_out_checklist_auth: true,
      warehouse_address_id: null,
      region: "South",
      zone: "Chennai Metro",
      created_at: now,
      created_on: now,
      created_by: "SYSTEM",
      updated_at: now,
      updated_on: now,
      updated_by: "SYSTEM",
      status: "PENDING",
    },
    {
      warehouse_id: "WH003",
      consignor_id: consignorId,
      warehouse_type: "Distributor",
      warehouse_name1: "Delhi Regional Distribution Center",
      warehouse_name2: "Delhi RDC",
      language: "English",
      vehicle_capacity: 100,
      virtual_yard_in: true,
      radius_for_virtual_yard_in: 3.0,
      speed_limit: 25,
      weigh_bridge_availability: false,
      gatepass_system_available: true,
      fuel_availability: true,
      staging_area_for_goods_organization: true,
      driver_waiting_area: true,
      gate_in_checklist_auth: true,
      gate_out_checklist_auth: true,
      warehouse_address_id: null,
      region: "North",
      zone: "NCR",
      created_at: now,
      created_on: now,
      created_by: "SYSTEM",
      updated_at: now,
      updated_on: now,
      updated_by: "SYSTEM",
      status: "PENDING",
    },
    {
      warehouse_id: "WH004",
      consignor_id: consignorId,
      warehouse_type: "Food Processing",
      warehouse_name1: "Bengaluru Food Processing Unit",
      warehouse_name2: "BLR FPU",
      language: "English",
      vehicle_capacity: 40,
      virtual_yard_in: true,
      radius_for_virtual_yard_in: 2.0,
      speed_limit: 20,
      weigh_bridge_availability: true,
      gatepass_system_available: true,
      fuel_availability: false,
      staging_area_for_goods_organization: true,
      driver_waiting_area: true,
      gate_in_checklist_auth: true,
      gate_out_checklist_auth: true,
      warehouse_address_id: null,
      region: "South",
      zone: "Bengaluru Metro",
      created_at: now,
      created_on: now,
      created_by: "SYSTEM",
      updated_at: now,
      updated_on: now,
      updated_by: "SYSTEM",
      status: "PENDING",
    },
    {
      warehouse_id: "WH005",
      consignor_id: consignorId,
      warehouse_type: "Assembling",
      warehouse_name1: "Kolkata Assembly Plant",
      warehouse_name2: "KOL Assembly",
      language: "English",
      vehicle_capacity: 60,
      virtual_yard_in: false,
      radius_for_virtual_yard_in: null,
      speed_limit: 20,
      weigh_bridge_availability: true,
      gatepass_system_available: true,
      fuel_availability: true,
      staging_area_for_goods_organization: true,
      driver_waiting_area: true,
      gate_in_checklist_auth: true,
      gate_out_checklist_auth: true,
      warehouse_address_id: null,
      region: "East",
      zone: "Kolkata Metro",
      created_at: now,
      created_on: now,
      created_by: "SYSTEM",
      updated_at: now,
      updated_on: now,
      updated_by: "SYSTEM",
      status: "PENDING",
    },
  ]);

  console.log(" Inserted 5 warehouses successfully");
};
