/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 *
 * Driver Test Data Seed
 * Creates 25 comprehensive driver records with addresses and documents
 * - Indian phone format (10 digits starting with 6-9)
 * - Addresses linked via tms_address table with DRIVER user type
 * - Driver documents (licenses, ID proofs)
 * - Diverse data for testing filters (gender, blood group, status, cities)
 */
exports.seed = async function (knex) {
  console.log("🚀 Starting Driver seed data insertion...");

  // Clean existing entries (in reverse order due to foreign keys)
  console.log("🧹 Cleaning existing driver data...");
  await knex("driver_accident_violation").del();
  await knex("driver_history_information").del();
  await knex("driver_documents").del();

  // Delete only driver addresses (not all addresses)
  await knex("tms_address").where("user_type", "DRIVER").del();

  await knex("driver_basic_information").del();

  const currentTimestamp = new Date();
  const currentUser = "SYSTEM";

  // ========================================
  // PART 1: INSERT ADDRESSES
  // ========================================
  console.log("📍 Inserting driver addresses...");

  const addresses = [
    // DRV0001-0005 - Maharashtra
    {
      address_id: "ADDR_DRV001",
      user_reference_id: "DRV0001",
      user_type: "DRIVER",
      country: "India",
      state: "Maharashtra",
      city: "Mumbai",
      district: "Mumbai Suburban",
      street_1: "123 Andheri West",
      postal_code: "400058",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV002",
      user_reference_id: "DRV0002",
      user_type: "DRIVER",
      country: "India",
      state: "Maharashtra",
      city: "Pune",
      district: "Pune",
      street_1: "456 Koregaon Park",
      postal_code: "411001",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV003",
      user_reference_id: "DRV0003",
      user_type: "DRIVER",
      country: "India",
      state: "Maharashtra",
      city: "Nagpur",
      district: "Nagpur",
      street_1: "789 Sadar",
      postal_code: "440001",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV004",
      user_reference_id: "DRV0004",
      user_type: "DRIVER",
      country: "India",
      state: "Maharashtra",
      city: "Thane",
      district: "Thane",
      street_1: "321 Ghodbunder Road",
      postal_code: "400601",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV005",
      user_reference_id: "DRV0005",
      user_type: "DRIVER",
      country: "India",
      state: "Maharashtra",
      city: "Nashik",
      district: "Nashik",
      street_1: "654 Sharanpur Road",
      postal_code: "422002",
      is_primary: true,
      address_type_id: "AT005",
    },

    // DRV0006-0010 - Karnataka
    {
      address_id: "ADDR_DRV006",
      user_reference_id: "DRV0006",
      user_type: "DRIVER",
      country: "India",
      state: "Karnataka",
      city: "Bangalore",
      district: "Bangalore Urban",
      street_1: "987 Koramangala",
      postal_code: "560034",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV007",
      user_reference_id: "DRV0007",
      user_type: "DRIVER",
      country: "India",
      state: "Karnataka",
      city: "Mysore",
      district: "Mysuru",
      street_1: "246 Saraswathipuram",
      postal_code: "570009",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV008",
      user_reference_id: "DRV0008",
      user_type: "DRIVER",
      country: "India",
      state: "Karnataka",
      city: "Hubli",
      district: "Dharwad",
      street_1: "135 Vidyanagar",
      postal_code: "580021",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV009",
      user_reference_id: "DRV0009",
      user_type: "DRIVER",
      country: "India",
      state: "Karnataka",
      city: "Mangalore",
      district: "Dakshina Kannada",
      street_1: "864 Kadri",
      postal_code: "575002",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV010",
      user_reference_id: "DRV0010",
      user_type: "DRIVER",
      country: "India",
      state: "Karnataka",
      city: "Belgaum",
      district: "Belgaum",
      street_1: "753 Tilakwadi",
      postal_code: "590006",
      is_primary: true,
      address_type_id: "AT005",
    },

    // DRV0011-0015 - Tamil Nadu
    {
      address_id: "ADDR_DRV011",
      user_reference_id: "DRV0011",
      user_type: "DRIVER",
      country: "India",
      state: "Tamil Nadu",
      city: "Chennai",
      district: "Chennai",
      street_1: "159 T Nagar",
      postal_code: "600017",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV012",
      user_reference_id: "DRV0012",
      user_type: "DRIVER",
      country: "India",
      state: "Tamil Nadu",
      city: "Coimbatore",
      district: "Coimbatore",
      street_1: "357 R S Puram",
      postal_code: "641002",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV013",
      user_reference_id: "DRV0013",
      user_type: "DRIVER",
      country: "India",
      state: "Tamil Nadu",
      city: "Madurai",
      district: "Madurai",
      street_1: "246 Anna Nagar",
      postal_code: "625020",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV014",
      user_reference_id: "DRV0014",
      user_type: "DRIVER",
      country: "India",
      state: "Tamil Nadu",
      city: "Trichy",
      district: "Tiruchirappalli",
      street_1: "468 Srirangam",
      postal_code: "620006",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV015",
      user_reference_id: "DRV0015",
      user_type: "DRIVER",
      country: "India",
      state: "Tamil Nadu",
      city: "Salem",
      district: "Salem",
      street_1: "579 Cherry Road",
      postal_code: "636007",
      is_primary: true,
      address_type_id: "AT005",
    },

    // DRV0016-0020 - Delhi, Gujarat, Rajasthan
    {
      address_id: "ADDR_DRV016",
      user_reference_id: "DRV0016",
      user_type: "DRIVER",
      country: "India",
      state: "Delhi",
      city: "New Delhi",
      district: "New Delhi",
      street_1: "891 Connaught Place",
      postal_code: "110001",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV017",
      user_reference_id: "DRV0017",
      user_type: "DRIVER",
      country: "India",
      state: "Gujarat",
      city: "Ahmedabad",
      district: "Ahmedabad",
      street_1: "234 Satellite",
      postal_code: "380015",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV018",
      user_reference_id: "DRV0018",
      user_type: "DRIVER",
      country: "India",
      state: "Gujarat",
      city: "Surat",
      district: "Surat",
      street_1: "567 Adajan",
      postal_code: "395009",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV019",
      user_reference_id: "DRV0019",
      user_type: "DRIVER",
      country: "India",
      state: "Rajasthan",
      city: "Jaipur",
      district: "Jaipur",
      street_1: "890 Malviya Nagar",
      postal_code: "302017",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV020",
      user_reference_id: "DRV0020",
      user_type: "DRIVER",
      country: "India",
      state: "Rajasthan",
      city: "Jodhpur",
      district: "Jodhpur",
      street_1: "123 Paota",
      postal_code: "342001",
      is_primary: true,
      address_type_id: "AT005",
    },

    // DRV0021-0025 - West Bengal, Telangana, Kerala
    {
      address_id: "ADDR_DRV021",
      user_reference_id: "DRV0021",
      user_type: "DRIVER",
      country: "India",
      state: "West Bengal",
      city: "Kolkata",
      district: "Kolkata",
      street_1: "456 Salt Lake",
      postal_code: "700064",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV022",
      user_reference_id: "DRV0022",
      user_type: "DRIVER",
      country: "India",
      state: "Telangana",
      city: "Hyderabad",
      district: "Hyderabad",
      street_1: "789 Banjara Hills",
      postal_code: "500034",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV023",
      user_reference_id: "DRV0023",
      user_type: "DRIVER",
      country: "India",
      state: "Kerala",
      city: "Kochi",
      district: "Ernakulam",
      street_1: "321 Marine Drive",
      postal_code: "682031",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV024",
      user_reference_id: "DRV0024",
      user_type: "DRIVER",
      country: "India",
      state: "Kerala",
      city: "Thiruvananthapuram",
      district: "Thiruvananthapuram",
      street_1: "654 Pattom",
      postal_code: "695004",
      is_primary: true,
      address_type_id: "AT005",
    },
    {
      address_id: "ADDR_DRV025",
      user_reference_id: "DRV0025",
      user_type: "DRIVER",
      country: "India",
      state: "West Bengal",
      city: "Howrah",
      district: "Howrah",
      street_1: "987 Shibpur",
      postal_code: "711102",
      is_primary: true,
      address_type_id: "AT005",
    },
  ];

  // Insert addresses with audit fields
  const addressesWithAudit = addresses.map((addr) => ({
    ...addr,
    created_at: currentTimestamp,
    created_on: currentTimestamp,
    created_by: currentUser,
    updated_at: currentTimestamp,
    updated_on: currentTimestamp,
    updated_by: currentUser,
    status: "ACTIVE",
  }));

  await knex("tms_address").insert(addressesWithAudit);
  console.log(`✅ Inserted ${addresses.length} driver addresses`);

  // ========================================
  // PART 2: INSERT DRIVER BASIC INFORMATION
  // ========================================
  console.log("👤 Inserting driver basic information...");

  const drivers = [
    // Mix of genders, blood groups, and ratings
    {
      driver_id: "DRV0001",
      full_name: "Rajesh Kumar Singh",
      date_of_birth: "1985-03-15",
      gender: "MALE",
      blood_group: "O+",
      phone_number: "9876543210",
      email_id: "rajesh.kumar@transportmail.in",
      whats_app_number: "9876543210",
      alternate_phone_number: "9876543211",
      avg_rating: 4.7,
    },
    {
      driver_id: "DRV0002",
      full_name: "Priya Sharma",
      date_of_birth: "1990-07-22",
      gender: "FEMALE",
      blood_group: "A+",
      phone_number: "9876543212",
      email_id: "priya.sharma@transportmail.in",
      whats_app_number: "9876543212",
      alternate_phone_number: "9876543213",
      avg_rating: 4.9,
    },
    {
      driver_id: "DRV0003",
      full_name: "Amit Patel",
      date_of_birth: "1988-11-08",
      gender: "MALE",
      blood_group: "B+",
      phone_number: "9876543214",
      email_id: "amit.patel@transportmail.in",
      whats_app_number: "9876543214",
      alternate_phone_number: "9876543215",
      avg_rating: 4.5,
    },
    {
      driver_id: "DRV0004",
      full_name: "Deepika Verma",
      date_of_birth: "1992-05-14",
      gender: "FEMALE",
      blood_group: "AB+",
      phone_number: "9876543216",
      email_id: "deepika.verma@transportmail.in",
      whats_app_number: "9876543216",
      alternate_phone_number: "9876543217",
      avg_rating: 4.8,
    },
    {
      driver_id: "DRV0005",
      full_name: "Suresh Reddy",
      date_of_birth: "1983-09-30",
      gender: "MALE",
      blood_group: "O-",
      phone_number: "9876543218",
      email_id: "suresh.reddy@transportmail.in",
      whats_app_number: "9876543218",
      alternate_phone_number: "9876543219",
      avg_rating: 4.6,
    },

    {
      driver_id: "DRV0006",
      full_name: "Anita Desai",
      date_of_birth: "1991-12-25",
      gender: "FEMALE",
      blood_group: "A-",
      phone_number: "9876543220",
      email_id: "anita.desai@transportmail.in",
      whats_app_number: "9876543220",
      alternate_phone_number: "9876543221",
      avg_rating: 4.7,
    },
    {
      driver_id: "DRV0007",
      full_name: "Vijay Kumar",
      date_of_birth: "1986-04-18",
      gender: "MALE",
      blood_group: "B-",
      phone_number: "9876543222",
      email_id: "vijay.kumar@transportmail.in",
      whats_app_number: "9876543222",
      alternate_phone_number: "9876543223",
      avg_rating: 4.4,
    },
    {
      driver_id: "DRV0008",
      full_name: "Meera Nair",
      date_of_birth: "1989-08-12",
      gender: "FEMALE",
      blood_group: "AB-",
      phone_number: "9876543224",
      email_id: "meera.nair@transportmail.in",
      whats_app_number: "9876543224",
      alternate_phone_number: "9876543225",
      avg_rating: 4.9,
    },
    {
      driver_id: "DRV0009",
      full_name: "Ravi Shankar",
      date_of_birth: "1984-02-28",
      gender: "MALE",
      blood_group: "O+",
      phone_number: "9876543226",
      email_id: "ravi.shankar@transportmail.in",
      whats_app_number: "9876543226",
      alternate_phone_number: "9876543227",
      avg_rating: 4.3,
    },
    {
      driver_id: "DRV0010",
      full_name: "Sunita Rao",
      date_of_birth: "1993-06-05",
      gender: "FEMALE",
      blood_group: "A+",
      phone_number: "9876543228",
      email_id: "sunita.rao@transportmail.in",
      whats_app_number: "9876543228",
      alternate_phone_number: "9876543229",
      avg_rating: 4.8,
    },

    {
      driver_id: "DRV0011",
      full_name: "Manoj Tiwari",
      date_of_birth: "1987-10-20",
      gender: "MALE",
      blood_group: "B+",
      phone_number: "8765432101",
      email_id: "manoj.tiwari@transportmail.in",
      whats_app_number: "8765432101",
      alternate_phone_number: "8765432102",
      avg_rating: 4.6,
    },
    {
      driver_id: "DRV0012",
      full_name: "Kavita Iyer",
      date_of_birth: "1990-01-15",
      gender: "FEMALE",
      blood_group: "O-",
      phone_number: "8765432103",
      email_id: "kavita.iyer@transportmail.in",
      whats_app_number: "8765432103",
      alternate_phone_number: "8765432104",
      avg_rating: 4.7,
    },
    {
      driver_id: "DRV0013",
      full_name: "Arun Krishnan",
      date_of_birth: "1985-03-22",
      gender: "MALE",
      blood_group: "A-",
      phone_number: "8765432105",
      email_id: "arun.krishnan@transportmail.in",
      whats_app_number: "8765432105",
      alternate_phone_number: "8765432106",
      avg_rating: 4.5,
    },
    {
      driver_id: "DRV0014",
      full_name: "Lakshmi Menon",
      date_of_birth: "1992-11-30",
      gender: "FEMALE",
      blood_group: "AB+",
      phone_number: "8765432107",
      email_id: "lakshmi.menon@transportmail.in",
      whats_app_number: "8765432107",
      alternate_phone_number: "8765432108",
      avg_rating: 4.9,
    },
    {
      driver_id: "DRV0015",
      full_name: "Sandeep Gupta",
      date_of_birth: "1988-07-08",
      gender: "MALE",
      blood_group: "B-",
      phone_number: "8765432109",
      email_id: "sandeep.gupta@transportmail.in",
      whats_app_number: "8765432109",
      alternate_phone_number: "8765432110",
      avg_rating: 4.4,
    },

    {
      driver_id: "DRV0016",
      full_name: "Neha Chopra",
      date_of_birth: "1991-09-17",
      gender: "FEMALE",
      blood_group: "O+",
      phone_number: "7654321012",
      email_id: "neha.chopra@transportmail.in",
      whats_app_number: "7654321012",
      alternate_phone_number: "7654321013",
      avg_rating: 4.8,
    },
    {
      driver_id: "DRV0017",
      full_name: "Karthik Bose",
      date_of_birth: "1986-12-03",
      gender: "MALE",
      blood_group: "A+",
      phone_number: "7654321014",
      email_id: "karthik.bose@transportmail.in",
      whats_app_number: "7654321014",
      alternate_phone_number: "7654321015",
      avg_rating: 4.6,
    },
    {
      driver_id: "DRV0018",
      full_name: "Pooja Mehta",
      date_of_birth: "1989-04-26",
      gender: "FEMALE",
      blood_group: "B+",
      phone_number: "7654321016",
      email_id: "pooja.mehta@transportmail.in",
      whats_app_number: "7654321016",
      alternate_phone_number: "7654321017",
      avg_rating: 4.7,
    },
    {
      driver_id: "DRV0019",
      full_name: "Rahul Joshi",
      date_of_birth: "1984-08-11",
      gender: "MALE",
      blood_group: "AB-",
      phone_number: "7654321018",
      email_id: "rahul.joshi@transportmail.in",
      whats_app_number: "7654321018",
      alternate_phone_number: "7654321019",
      avg_rating: 4.5,
    },
    {
      driver_id: "DRV0020",
      full_name: "Swati Agarwal",
      date_of_birth: "1993-02-19",
      gender: "FEMALE",
      blood_group: "O-",
      phone_number: "7654321020",
      email_id: "swati.agarwal@transportmail.in",
      whats_app_number: "7654321020",
      alternate_phone_number: "7654321021",
      avg_rating: 4.9,
    },

    {
      driver_id: "DRV0021",
      full_name: "Abhishek Banerjee",
      date_of_birth: "1987-05-07",
      gender: "MALE",
      blood_group: "A-",
      phone_number: "6543210123",
      email_id: "abhishek.banerjee@transportmail.in",
      whats_app_number: "6543210123",
      alternate_phone_number: "6543210124",
      avg_rating: 4.3,
    },
    {
      driver_id: "DRV0022",
      full_name: "Divya Pillai",
      date_of_birth: "1990-10-14",
      gender: "FEMALE",
      blood_group: "B-",
      phone_number: "6543210125",
      email_id: "divya.pillai@transportmail.in",
      whats_app_number: "6543210125",
      alternate_phone_number: "6543210126",
      avg_rating: 4.8,
    },
    {
      driver_id: "DRV0023",
      full_name: "Prakash Nambiar",
      date_of_birth: "1985-06-29",
      gender: "MALE",
      blood_group: "O+",
      phone_number: "6543210127",
      email_id: "prakash.nambiar@transportmail.in",
      whats_app_number: "6543210127",
      alternate_phone_number: "6543210128",
      avg_rating: 4.6,
    },
    {
      driver_id: "DRV0024",
      full_name: "Anjali Sinha",
      date_of_birth: "1992-03-16",
      gender: "FEMALE",
      blood_group: "A+",
      phone_number: "6543210129",
      email_id: "anjali.sinha@transportmail.in",
      whats_app_number: "6543210129",
      alternate_phone_number: "6543210130",
      avg_rating: 4.7,
    },
    {
      driver_id: "DRV0025",
      full_name: "Sanjay Mukherjee",
      date_of_birth: "1988-12-21",
      gender: "MALE",
      blood_group: "AB+",
      phone_number: "6543210131",
      email_id: "sanjay.mukherjee@transportmail.in",
      whats_app_number: "6543210131",
      alternate_phone_number: "6543210132",
      avg_rating: 4.4,
    },
  ];

  // Insert drivers with audit fields
  const driversWithAudit = drivers.map((driver) => ({
    ...driver,
    created_at: currentTimestamp,
    created_on: currentTimestamp,
    created_by: currentUser,
    updated_at: currentTimestamp,
    updated_on: currentTimestamp,
    updated_by: currentUser,
    status: "ACTIVE",
  }));

  await knex("driver_basic_information").insert(driversWithAudit);
  console.log(`✅ Inserted ${drivers.length} drivers`);

  // ========================================
  // PART 3: INSERT DRIVER DOCUMENTS
  // ========================================
  console.log("📄 Inserting driver documents...");

  const documents = [
    // Driver licenses for first 15 drivers
    {
      document_unique_id: "DOC-DRV0001-LIC",
      document_id: "DDOC0001",
      driver_id: "DRV0001",
      document_type_id: "DOC002",
      document_number: "MH-0120230001234",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2023-01-15",
      valid_to: "2043-01-14",
      remarks: "Heavy Motor Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0002-LIC",
      document_id: "DDOC0002",
      driver_id: "DRV0002",
      document_type_id: "DOC002",
      document_number: "MH-0220230002345",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2023-03-10",
      valid_to: "2043-03-09",
      remarks: "Transport Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0003-LIC",
      document_id: "DDOC0003",
      driver_id: "DRV0003",
      document_type_id: "DOC002",
      document_number: "MH-0320230003456",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2022-11-20",
      valid_to: "2042-11-19",
      remarks: "Commercial Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0004-LIC",
      document_id: "DDOC0004",
      driver_id: "DRV0004",
      document_type_id: "DOC002",
      document_number: "MH-0420230004567",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2023-05-05",
      valid_to: "2043-05-04",
      remarks: "Heavy Goods Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0005-LIC",
      document_id: "DDOC0005",
      driver_id: "DRV0005",
      document_type_id: "DOC002",
      document_number: "MH-0520230005678",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2023-02-18",
      valid_to: "2043-02-17",
      remarks: "Transport License - All Categories",
    },

    {
      document_unique_id: "DOC-DRV0006-LIC",
      document_id: "DDOC0006",
      driver_id: "DRV0006",
      document_type_id: "DOC002",
      document_number: "KA-0120230006789",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2023-04-12",
      valid_to: "2043-04-11",
      remarks: "Commercial Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0007-LIC",
      document_id: "DDOC0007",
      driver_id: "DRV0007",
      document_type_id: "DOC002",
      document_number: "KA-0220230007890",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2023-06-22",
      valid_to: "2043-06-21",
      remarks: "Heavy Transport Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0008-LIC",
      document_id: "DDOC0008",
      driver_id: "DRV0008",
      document_type_id: "DOC002",
      document_number: "KA-0320230008901",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2022-09-15",
      valid_to: "2042-09-14",
      remarks: "All Vehicle Classes License",
    },
    {
      document_unique_id: "DOC-DRV0009-LIC",
      document_id: "DDOC0009",
      driver_id: "DRV0009",
      document_type_id: "DOC002",
      document_number: "KA-0420230009012",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2023-01-28",
      valid_to: "2043-01-27",
      remarks: "Commercial Transport License",
    },
    {
      document_unique_id: "DOC-DRV0010-LIC",
      document_id: "DDOC0010",
      driver_id: "DRV0010",
      document_type_id: "DOC002",
      document_number: "KA-0520230010123",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2023-03-05",
      valid_to: "2043-03-04",
      remarks: "Heavy Goods Vehicle License",
    },

    {
      document_unique_id: "DOC-DRV0011-LIC",
      document_id: "DDOC0011",
      driver_id: "DRV0011",
      document_type_id: "DOC002",
      document_number: "TN-0120230011234",
      issuing_country: "India",
      issuing_state: "Tamil Nadu",
      active_flag: true,
      valid_from: "2022-12-10",
      valid_to: "2042-12-09",
      remarks: "Transport Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0012-LIC",
      document_id: "DDOC0012",
      driver_id: "DRV0012",
      document_type_id: "DOC002",
      document_number: "TN-0220230012345",
      issuing_country: "India",
      issuing_state: "Tamil Nadu",
      active_flag: true,
      valid_from: "2023-02-25",
      valid_to: "2043-02-24",
      remarks: "Commercial Transport License",
    },
    {
      document_unique_id: "DOC-DRV0013-LIC",
      document_id: "DDOC0013",
      driver_id: "DRV0013",
      document_type_id: "DOC002",
      document_number: "TN-0320230013456",
      issuing_country: "India",
      issuing_state: "Tamil Nadu",
      active_flag: true,
      valid_from: "2023-05-18",
      valid_to: "2043-05-17",
      remarks: "Heavy Motor Vehicle License",
    },
    {
      document_unique_id: "DOC-DRV0014-LIC",
      document_id: "DDOC0014",
      driver_id: "DRV0014",
      document_type_id: "DOC002",
      document_number: "TN-0420230014567",
      issuing_country: "India",
      issuing_state: "Tamil Nadu",
      active_flag: true,
      valid_from: "2023-07-03",
      valid_to: "2043-07-02",
      remarks: "All Categories Transport License",
    },
    {
      document_unique_id: "DOC-DRV0015-LIC",
      document_id: "DDOC0015",
      driver_id: "DRV0015",
      document_type_id: "DOC002",
      document_number: "TN-0520230015678",
      issuing_country: "India",
      issuing_state: "Tamil Nadu",
      active_flag: true,
      valid_from: "2022-10-20",
      valid_to: "2042-10-19",
      remarks: "Commercial Vehicle License",
    },

    // Aadhaar cards for drivers 1-10
    {
      document_unique_id: "DOC-DRV0001-AAD",
      document_id: "DDOC0026",
      driver_id: "DRV0001",
      document_type_id: "DN002",
      document_number: "4123-5678-9012",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2015-01-01",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0002-AAD",
      document_id: "DDOC0027",
      driver_id: "DRV0002",
      document_type_id: "DN002",
      document_number: "5234-6789-0123",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2016-02-15",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0003-AAD",
      document_id: "DDOC0028",
      driver_id: "DRV0003",
      document_type_id: "DN002",
      document_number: "6345-7890-1234",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2015-05-10",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0004-AAD",
      document_id: "DDOC0029",
      driver_id: "DRV0004",
      document_type_id: "DN002",
      document_number: "7456-8901-2345",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2017-03-20",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0005-AAD",
      document_id: "DDOC0030",
      driver_id: "DRV0005",
      document_type_id: "DN002",
      document_number: "8567-9012-3456",
      issuing_country: "India",
      issuing_state: "Maharashtra",
      active_flag: true,
      valid_from: "2016-08-12",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0006-AAD",
      document_id: "DDOC0031",
      driver_id: "DRV0006",
      document_type_id: "DN002",
      document_number: "9678-0123-4567",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2015-11-25",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0007-AAD",
      document_id: "DDOC0032",
      driver_id: "DRV0007",
      document_type_id: "DN002",
      document_number: "1789-1234-5678",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2016-06-30",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0008-AAD",
      document_id: "DDOC0033",
      driver_id: "DRV0008",
      document_type_id: "DN002",
      document_number: "2890-2345-6789",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2017-01-18",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0009-AAD",
      document_id: "DDOC0034",
      driver_id: "DRV0009",
      document_type_id: "DN002",
      document_number: "3901-3456-7890",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2015-09-22",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
    {
      document_unique_id: "DOC-DRV0010-AAD",
      document_id: "DDOC0035",
      driver_id: "DRV0010",
      document_type_id: "DN002",
      document_number: "4012-4567-8901",
      issuing_country: "India",
      issuing_state: "Karnataka",
      active_flag: true,
      valid_from: "2016-12-05",
      valid_to: null,
      remarks: "Aadhaar Card",
    },
  ];

  // Insert documents with audit fields
  const documentsWithAudit = documents.map((doc) => ({
    ...doc,
    created_at: currentTimestamp,
    created_on: currentTimestamp,
    created_by: currentUser,
    updated_at: currentTimestamp,
    updated_on: currentTimestamp,
    updated_by: currentUser,
    status: "ACTIVE",
  }));

  await knex("driver_documents").insert(documentsWithAudit);
  console.log(`✅ Inserted ${documents.length} driver documents`);

  // ========================================
  // PART 4: INSERT DRIVER HISTORY (Optional - for 5 drivers)
  // ========================================
  console.log("📋 Inserting driver employment history...");

  const histories = [
    {
      driver_history_id: "HIST-DRV0001-001",
      driver_id: "DRV0001",
      employer: "Express Logistics Pvt Ltd",
      from_date: "2020-01-15",
      to_date: "2023-12-31",
      employment_status: "Full-time",
      job_title: "Long Haul Driver",
    },
    {
      driver_history_id: "HIST-DRV0001-002",
      driver_id: "DRV0001",
      employer: "Global Transport Solutions",
      from_date: "2024-01-01",
      to_date: null,
      employment_status: "Full-time",
      job_title: "Senior Driver - Regional Routes",
    },
    {
      driver_history_id: "HIST-DRV0002-001",
      driver_id: "DRV0002",
      employer: "Swift Transport Services",
      from_date: "2021-03-01",
      to_date: null,
      employment_status: "Full-time",
      job_title: "Commercial Vehicle Driver",
    },
    {
      driver_history_id: "HIST-DRV0003-001",
      driver_id: "DRV0003",
      employer: "Rapid Freight Systems",
      from_date: "2019-06-15",
      to_date: "2023-05-31",
      employment_status: "Full-time",
      job_title: "Heavy Vehicle Driver",
    },
    {
      driver_history_id: "HIST-DRV0003-002",
      driver_id: "DRV0003",
      employer: "Metro Logistics Ltd",
      from_date: "2023-06-01",
      to_date: null,
      employment_status: "Full-time",
      job_title: "Lead Driver",
    },
  ];

  const historiesWithAudit = histories.map((hist) => ({
    ...hist,
    created_at: currentTimestamp,
    created_on: currentTimestamp,
    created_by: currentUser,
    updated_at: currentTimestamp,
    updated_on: currentTimestamp,
    updated_by: currentUser,
  }));

  await knex("driver_history_information").insert(historiesWithAudit);
  console.log(`✅ Inserted ${histories.length} employment history records`);

  console.log("🎉 Driver seed data insertion completed successfully!");
  console.log(`
  📊 Summary:
  - ${addresses.length} Addresses created
  - ${drivers.length} Drivers created
  - ${documents.length} Documents uploaded
  - ${histories.length} Employment history records
  
  🔍 Test Coverage:
  - Gender: MALE (13), FEMALE (12)
  - Blood Groups: All 8 types (O+, O-, A+, A-, B+, B-, AB+, AB-)
  - States: Maharashtra, Karnataka, Tamil Nadu, Delhi, Gujarat, Rajasthan, West Bengal, Telangana, Kerala
  - Cities: 20+ different cities across India
  - Phone Numbers: Indian format (10 digits, starting with 6-9)
  - Status: All ACTIVE
  `);
};
